name: "build, run and analyze fastfetch"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  default:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update and install packages
      run: sudo apt-get update && sudo apt upgrade && sudo apt-get install -y libpci-dev libvulkan-dev libwayland-dev libxrandr-dev libxcb-randr0-dev libdconf-dev libdbus-1-dev libxfconf-0-dev librpm-dev libzstd-dev

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Configure
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

    - name: Build
      run: cmake --build .

    - name: Run fastfetch
      run: ./fastfetch

    - name: Run fastfetch-test-strbuf
      run: ./fastfetch-test-strbuf

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
