name: manage pull requests

on: pull_request

jobs:
  check:
    name: manage pull request
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: run build and check
        uses: ./.github/workflows/check
