name: manage pull requests

on: pull_request

jobs:
  manage:
    name: manage pull request
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: run build and check
        uses: LinusDierheimer/fastfetch/.github/workflows/check.yml@master
