name: Build, Run and Analyze fastfetch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  check:
    name: Build, Run and Analyze fastfetch
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update and install packages
      run: sudo apt-get update && sudo apt-get install -y libpci-dev libvulkan-dev libwayland-dev libxrandr-dev libxcb-randr0-dev libdconf-dev libdbus-1-dev libxfconf-0-dev librpm-dev libzstd-dev

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Configure
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

    - name: Build
      run: cmake --build . -j$(nproc)

    - name: Run fastfetch
      run: ./fastfetch --recache --disable-linewrap false --hide-cursor false --show-errors true

    - name: Run flashfetch
      run: ./flashfetch

    - name: Run tests
      run: ctest

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

    - name: Build deb package
      run: sh packaging/deb/create.sh .

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: fastfetch
        path: ./fastfetch

    - name: Upload deb package
      uses: actions/upload-artifact@v2
      with:
        name: fastfetch.deb
        path: ./packaging/deb/fastfetch.deb
